version: "3.3"

volumes:
  pg_data:
  static:
  media:
services:
  frontend:
    build: ../frontend
    volumes:
      - static:/result_build
    depends_on:
      - backend

  db:
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 3s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ../backend
    env_file: ../.env
    volumes:
      - static:/collected_static
      - media:/app/media/
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:1.25.4-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/staticfiles
      - media:/app/media/
    depends_on:
      - backend
      - frontend
